export { Stats } from './Component'
export { statsPlaceholder } from './placeholder'
export { StatsGlobal } from './config'
export { adaptStats } from './adapt'
export type { StatsProps, Stat } from './types'
